dyc/DYC/WSD.Dyc.WebApp/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WSD.Dyc.BusinessLogic;
using WSD.Dyc.Core.Contracts;
using WSD.Dyc.Domain.Models;
using WSD.Dyc.WebApp.Helpers;

namespace WSD.Dyc.WebApp.Controllers
{
    [SecureContextHeader]
    [AuthorizationHeader]
    public class MembersController : Controller
    {
        private IAppBusinessLogic _logic;
        public MembersController()
        {
            _logic = new AppBusinessLogic(ConfigurationManager.ConnectionStrings["ConnString"].ConnectionString);
        }

        // GET: Members
        [HttpGet]
        public ActionResult Dashboard()
        {
            return View();
        }
        [HttpGet]
        public ActionResult MyProfile()
        {
            return
                View((MemberModel)Session["Member"]);
        }
        [HttpPost]
        public ActionResult MyProfile(MemberModel member)
        {
            try
            {
                var m = ((MemberModel)Session["Member"]);
                member.MemberId = m.MemberId;
                member.IsDisabled = m.IsDisabled;
                member.MemberCode = m.MemberCode;
                if (Request.Files.Count > 0)
                {
                    var c = Request.Files[0].ContentLength;
                    var reader = new BinaryReader(Request.Files[0].InputStream);
                    member.ProfileImage = reader.ReadBytes(c);
                    reader.Close();
                }
                _logic.AddOrUpdateMembers(member);
                Session["Member"] = member;
                return
                    RedirectToAction("Dashboard");
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(member);
            }
        }
        [HttpGet]
        public ActionResult Gallery()
        {
            var total = 0;
            var m = _logic.GetAllImages(0, int.MaxValue, out total);
            ViewBag.Total = total;
            return
                View(m);
        }

        [HttpPost]
        public ActionResult PostImage(string img64)
        {
            try
            {
                if(img64.StartsWith("data/png:"))
                {
                    img64 = img64.Substring(9);
                }
                var imgBits = Convert.FromBase64String(img64);
                _logic.AddOrUpdateImage(new ImageModel
                {
                    ImageContent = imgBits,
                    Member = ((MemberModel)Session["Member"])
                });
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return
                    Json(new {Error = ex.Message, Success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult FacebookProfilePicUpload(string imgUrl)
        {
            var client = new WebClient();
            var imgBits = client.DownloadData(imgUrl);
            try
            { 
                _logic.AddOrUpdateImage(new ImageModel
                {
                    ImageContent = imgBits,
                    Member = ((MemberModel)Session["Member"])
                });
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return
                    Json(new { Error = ex.Message, Success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult PostImage()
        {
            return
                View();
        }    
    }
}

dyc/DYC/WSD.Dyc.WebApp/Views/Members/Dashboard.cshtml
 
@{
    ViewBag.Title = "Member Dash Board";
}

<h2>Dash Board</h2>

<a href="/Members/Gallery"><img src="~/Content/galleryicon.jpg" alt="Gallery Link" width="200" height="200" /></a>
<br/>
<a href="/Home/CalendarEvents"><img src="~/Content/edit-event.png" width="200" height="200" alt="Calendar Events" /></a>
<br />
<a href="/Members/MyProfile"><img src="~/Content/profileicon.png" width="200" height="200" alt="My Profile" /></a>
<br/>

dyc/DYC/WSD.Dyc.WebApp/Views/Members/Gallery.cshtml
@model IEnumerable<WSD.Dyc.Domain.Models.ImageModel>

@{
    ViewBag.Title = "Gallery";
}

<h2>Gallery</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Gallery
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.Raw(WSD.Dyc.WebApp.Helpers.HtmlExtensions.ImageToImageTag(item.ImageContent, 200, 200, "Picture", item.ImageId.ToString()))
        </td>
       
    </tr>
}

</table>

dyc/DYC/WSD.Dyc.WebApp/Views/Members/MyProfile.cshtml
@model WSD.Dyc.Domain.Models.MemberModel

@{
    ViewBag.Title = "My Profile";
}

<h2>My Profile</h2>


@using (Html.BeginForm("MyProfile", "Members", FormMethod.Post, new { enctype = "multipart/form-data", id = "MyProfileForm" }))
{
    <div class="form-horizontal">
        <h4>Member Information</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OptOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.OptOut)
                    @Html.ValidationMessageFor(model => model.OptOut, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.MemberId)
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label for="Picture" class="control-label"> New Profile Picture</label>
            <div>
                <input type="file" accept="images/png" id="Picture" name="Picture" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Dashboard", "Dashboard")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dyc/DYC/WSD.Dyc.WebApp/Views/Members/PostImage.cshtml
@{
    ViewBag.Title = "Post Image";
}

<script type="text/javascript" src="~/Scripts/facebookapi.js"></script>
<script type="text/javascript" src="~/Scripts/ImageApi.js"></script>
<script type="text/javascript">
    function LoginAndErase()
    {
        $('#facebookimages').html('');
        Login();
    }
    $(document).ready(function () {
        $('#btnShowFacebookImporter').click(function () {
            
            $('#facebookImport').dialog({
                autoOpen: true,
                height: auto,
                width: auto
            });
        });
    });
</script>
<h2>Post Image</h2>

<div id="facebookImport">
    <input type="button" value="Upload Selected Images" id="facebookUpload" />
    <ul style="list-style-type:none;" id="facebookimages"></ul>
    <a href="#" onclick="LoginAndErase();">Get Facebook Images</a>

</div>
<div>
    Choose A File From Your PC:
    <br/>
    <input type="file" id="fileuploader" class="form-control" accept="images/png"/>
    <br/>
    <canvas id="imgCanvas" width="200" height="200" />
</div>
<div>
    <input type="button" id="btnShowFacebookImporter" value="Facebook Images..." class="btn btn-default" />
  
</div>